### PR TITLE
 Add comments and codes based on ETSI EN 300 401 V2.1.1 (2017-01)

### PR DESCRIPTION
**Pull request by pr2git**

### CODE REVIEW

**Comment by andimik** [comment]
Why closed?

**Comment by JvanKatwijk** [comment]
I have taken most of the proposed changes. Adding paragraph numbers to the functions is really useful, thanks. Some changes are not taken over,  I was surprised to see so many changes in the 2017-01 version. A few checks to be done  and the changes will appear in the github version tomorrow

**Comment by andimik** [comment]
Ok, understood :-)

**Comment by pr2git** [comment]
Thanks Jan to have understood the goal of the proposed changes.

**Pull request closed without merging**
